spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/anf
    username: ""
    password: ""
  jpa:
    show-sql: false

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
 