spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/anf
    username: ""
    password: ""
  jpa:
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
