spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/anf
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_OAUTH_CLIENT_ID}"
            client-secret: "${GOOGLE_OAUTH_CLIENT_SECRET}"
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO